apiVersion: v1
kind: Service
metadata:
  name: postgre
  namespace: duckbank
  labels:
    app: postgre
spec:
  selector:
    app: postgre
  ports:
    - port: 5432
      targetPort: 5432
      name: postgre
  type: ClusterIP
