services:
  postgres:
    image: postgres:17
    container_name: postgres
    restart: always
    tty: true
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: duckbank
      POSTGRES_USER: duckuser
      POSTGRES_PASSWORD: kgb8y2kk
volumes:
  postgres:
    driver: local
